#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
      path: /optionGroup
      controller: App\Controller\ChooseOptionGroupController::index


accueil:
      path: /home
      controller: App\Controller\AccueilController::index

index2:
      path: /createProject
      controller: App\Controller\CreateProjectController::index

addGroups:
      path: /addGroups
      controller: App\Controller\AddGroupsController::index
